### PR TITLE
adding run on repl.it badge

### PR DESCRIPTION
**Pull request by cram678**
this commit was generated automatically on repl.it

### CODE REVIEW

**Comment by ben-bay** [comment]
@cram678 what's going here?

**Comment by MrEconomical** [comment]
repl.it is a free online IDE that can run stuff, and right now they are in the process of adding the ability to run github repos. this could also be a solution for the hosting issue. this is a pull request to add the repl.it button in the readme to go to the repl.it site where they can run the repo

**Comment by ben-bay** [comment]
Cool, if we can demonstrate this works we'll add it.

**Comment by MrEconomical** [comment]
this guy forgot to configure his repl correctly, so it won't work. want me to make another one?

**Comment by ben-bay** [comment]
Closing this until we can get more clarity on it.

**Comment by cram678** [comment]
Sorry about this I was just attempting to test out the system I didnt realize this was going to send a pr no need to reopen

**Pull request closed without merging**
