### PR TITLE
Separate download torrent from install script

### PR DESCRIPTION
**Pull request by louisgv**
While trying to make the game more accessible, I found that coupling install and download model causes a lot of headache. This PR seeks to separate them so that user can pick the method they would like to get the model.

### CODE REVIEW

**Comment by louisgv** [comment]
Just realized this will conflict with #93 ...

**Comment by dyc3** [comment]
Yeah, I was just about to comment that. IMO, I don't think it's necessary to split the installer and the model download like this. If there is *really* a need for it, then we can add optional command line flags to skip steps in the install script

**Comment by louisgv** [comment]
@dyc3 I think it is necessary to do so, because as I went through your PR, I found that the logic checking for dependency can get large (i.e, the part where user is instructed to install python3.6).

I think splitting them make more sense when you look from the perspective of running this game from a notebook environment like google collab. I think it is easier to reason about the error and debug it when these feature are separated into separate script.

One problem I faced recently was when the runtime on collab expire and I have to reconnect the instance, the git clone and folder are there, but the runtime has no dependency installation. The install script failed to recognize that and thus it does not run `pip install`.

**Comment by dyc3** [comment]
I've never encountered that. Usually, if the collab session expires I just rerun all the blocks and it works just fine

**Comment by ben-bay** [comment]
Hey #93 was merged to develop, can you look at the conflict that causes?

**Comment by louisgv** [comment]
Yup will do!

**Comment by louisgv** [comment]
@ben-bay Should be good for review

**Comment by ben-bay** [comment]
Since the model is such a bear, I like the decomposition here. Before merge, can you add this to `CHANGELOG.md` under [Unreleased] (probably counts as a "Change")?

**Comment by godofgrunts** [comment]
Probably should inform the user to run `download_model.sh` to make it more clear.

**Pull request merged**
