### PR TITLE
Fix "Notebook loading error" on colab

### PR DESCRIPTION
**Pull request by wwboyer**
There was a missing comma after the array element on line 46, so I added it. From what I can tell, this was causing the colab to be unable to load.

### CODE REVIEW

**Comment by bdice** [comment]
Resolves #79. @wwboyer You also have to remove the comma on line 48, I think. I tried loading your version in colab and it failed: `JSON.parse: unexpected character at line 48 column 7 of the JSON data`.

Try it here: https://colab.research.google.com/github/wwboyer/AIDungeon/blob/patch-1/AIDungeon_2.ipynb

**Comment by wwboyer** [comment]
You're absolutely right. Fix one typo and forget about another. _Now_ it should be good, at least as far as I can tell.

**Comment by nickwalton** [comment]
Sorry guys!

**Comment by wwboyer** [comment]
No biggie, if I had a nickle for everytime I missed a comma, I'd be a rich man.

**Pull request merged**
