### PR TITLE
Google drive shared folder model

### PR DESCRIPTION
**Pull request by Akababa**
Link to try it: https://colab.research.google.com/github/Akababa/AIDungeon/blob/patch-2/AIDungeon_2.ipynb
The shared folder (view only) is from my google drive now. Feel free to change it to your own @nickwalton 
It's a few extra steps to set up but the benefit is there's no download required.
Tested on another google account.

### CODE REVIEW

**Comment by MCterra10** [comment]
doesn't google drive disable access to shared files that get downloaded too much?

**Comment by Akababa** [comment]
> doesn't google drive disable access to shared files that get downloaded too much?

Not sure as I haven't had a chance to test it on a larger scale. This won't be downloaded though as it's just a single shared folder so at least it won't be taking up Google's bandwidth.

**Comment by Couls** [comment]
Tested this myself as well and it works with colab
image

**Comment by MCterra10** [comment]
> 
> 
> > doesn't google drive disable access to shared files that get downloaded too much?
> 
> Not sure as I haven't had a chance to test it on a larger scale. This won't be downloaded though as it's just a single shared folder so at least it won't be taking up Google's bandwidth.

I've had experience downloading a lot of popular files, there's a well known trick of making a copy of the file to your own google drive and downloading from there because the file gets ratelimited pretty quick. I'd expect that if this gets merged it's gonna get shut down pretty quick.

**Comment by Akababa** [comment]
@MCterra10 That's most likely due to copyright issues or bandwidth costs on Google's part. Mounting a shared folder in Colab doesn't use any bandwidth. The only potential problem I see is if tons of people find the shared folder link and spam download it to their own computers... but there's no way it can be worse than every colab instance downloading a copy.

**Comment by WAUthethird** [comment]
This method is superior to mine in every way.

**Comment by JillCrungus** [comment]
I can't get this to work on my end, steps complete properly and I can see the files in the right place but TensorFlow spits out an error during initialisation.

image

**Comment by nickwalton** [comment]
So what's the conscensus does this work?

**Comment by JillCrungus** [comment]
> So what's the conscensus does this work?

Seems to work for some people out of the box but to get it to work for me I had to manually make copies of all of the model files into my drive (instead of just using the shared folder) or the program would fail with an I/O error when trying to access them.

**Comment by nickwalton** [comment]
Yeah that's what I'm worried about. I initially had the colab file in my
google drive folder and eventually that got locked and no one could
download it from too many people trying to.

**Comment by JillCrungus** [comment]
Just tried making a copy of the notebook in my own drive and it still didn't work, only way I can make it work for me is the previously described method of manually copying the model files themselves into my drive. Not ideal but I guess better than nothing? Assuming that doesn't result in the model files getting locked.

**Comment by Akababa** [comment]
I just tried on another google account and got the same OSError. I was able to google it and it seems to be some bug in colab.

> Yeah that's what I'm worried about. I initially had the colab file in my google drive folder and eventually that got locked and no one could download it from too many people trying to.

Is that the colab file or the model file? there shouldn't be any issue with getting locked anymore because colab file is hosted on github right?

**Comment by Akababa** [comment]
Ohh I think I know what the issue is. When Colab reads the file from the GDrive mount, it hits GCS as a download so it counts against the download quota. A few solutions:

1. Load balance by using multiple google drive shared folders
2. Ask someone at google for help
3. Get everyone to make a copy in their GDrive and use up their own storage

**Comment by JillCrungus** [comment]
> Ohh I think I know what the issue is. When Colab reads the file from the GDrive mount, it hits GCS as a download so it counts against the download quota. A few solutions:
> 
> 1. Load balance by using multiple google drive shared folders
> 2. Ask someone at google for help
> 3. Get everyone to make a copy in their GDrive and use up their own storage

I can see 1 becoming really inconvenient and I think depending on how many folders are used they'd all be used up eventually with how much traffic is going to come to the site.

Google's only response would likely be along the lines of "Well you know we have X and Y services you could pay for to host the files..." or something like that, I don't see them being much help.

Number 3 would definitely inconvenience some users and would be hard to explain I think but in the end, of the 3 options, it seems like the one that'd be most likely to work out. It's definitely not a terrible solution as long as this whole Google Drive thing is just a temporary measure while costs for better solutions etc. are sorted out.

**Comment by nickwalton** [comment]
I'm in talks with some people at Google, it seems like the long term
solution is going to be to have a hosted app that people can play the game
on. Might have to charge to cover costs but then the UI would be cleaner.
In that case I could probably open up the model for download again for
people who want to run it locally or tinker since the costs would be
significantly less then.

**Comment by Akababa** [comment]
@nickwalton Should I keep the shared folder up and change the instructions to "make a copy", or do you prefer using the torrents for now?

**Comment by Akababa** [comment]
Sorry I messed it up by accident, but it seems this isn't necessary anymore so I'll close

**Comment by MCterra10** [comment]
yeah, torrent swarm is very healthy currently, downloading in about a minute

**Comment by nickwalton** [comment]
Awesome! Good work guys!

**Comment by HoboBox** [comment]
will the 'official' version learn from all the different games being played? I figure that's the reason behind the 1-10 rating, right?

**Comment by nickwalton** [comment]
Yep that's the plan!

**Comment by HoboBox** [comment]
That's unreal. Can't wait for the release.

**Comment by sbrichardson** [comment]
I'm seeding the torrent file on 1gb/s fiber link currently. Appreciate your work.

**Pull request closed without merging**
