### PR TITLE
Making installation script more robust:

### PR DESCRIPTION
**Pull request by paul-nelson-baker**
- Updated script SHEBANG to point to env instead of directly to bash. This allows end systems to start with the appropriate bash installation (in case a different version is installed to a different location)
- Script creates virtual environment for python3, this mitigates the need to manually check for python3 and safely isolates the installation of packages from the system's packages
- Changed the way the installer detects package managers. Prior way checked for a the presence of a folder and assumed the os, which then assumed the installation command. If we check for the installation command directly, we make fewer asumptions and have the flexibility to check for different package managers in a miriade of ways (some OSes can have different package managers. EG: osx can have homebrew or macports.)
- Added shebangs to python scripts, they can utilize the appropriate python. When the venv python is activate, env will use it.

### CODE REVIEW

**Comment by ben-bay** [comment]
This looks really good. The one problem is that I think tensorflow v1.15 can only run up to python 3.6 (isn't that true?). If so, can you somehow preserve the message that checks for that and explains what to do if the version is incompatible?

**Comment by GatoCreador887** [comment]
It works for me using python 3.7.5 with tensorflow 1.15 on Linux.

**Comment by ben-bay** [comment]
@paul-nelson-baker hey I may have merged this prematurely, because at https://colab.research.google.com/github/AIDungeon/AIDungeon/blob/develop/AIDungeon_2.ipynb when I replace `--branch master` with `--branch develop`, I get this:

```
Cloning into 'AIDungeon'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 54 (delta 2), reused 18 (delta 0), pack-reused 0
Unpacking objects: 100% (54/54), done.
/content/AIDungeon
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/content/AIDungeon/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Installation Complete!
```

Any idea why?

**Comment by paul-nelson-baker** [comment]
@ben-bay Apologies, after your first comment I set out to see if I could do what you asked me before the merge. Lemme try and see what happened, because that's a strange error

**Comment by paul-nelson-baker** [comment]
@ben-bay Can you try again? I'm succeeding under those conditions. Has this been un-merged?
image

**Comment by ben-bay** [comment]
@paul-nelson-baker I think that was a mistake. Working on getting this back up, sorry

**Comment by louisgv** [comment]
@paul-nelson-baker Can you remove the clear_output() and try again? Your colab notebook is not the latest so it clear all of the error :p

**Pull request merged**
