### PR TITLE
windows compat

### PR DESCRIPTION
**Pull request by Akababa**
removes termios
#59

### CODE REVIEW

**Comment by ben-bay** [comment]
Hey thanks for this, can you describe the before and after behavior of this for someone who doesn't have access to Windows (me)?

**Comment by oafx** [comment]
You mind if I do it to speed things up?

## current behavior

trying to run this application on windows fails with an `ModuleNotFoundError: No module named 'termios'` error.

## expected behavior

the application should start without errors.

p.s. @Akababa interesting work on your fork ❤️

**Comment by ben-bay** [comment]
> You mind if I do it to speed things up?
> ## current behavior
> 
> trying to run this application on windows fails with an `ModuleNotFoundError: No module named 'termios'` error.
> ## expected behavior
> 
> the application should start without errors.
> 
> p.s. @Akababa interesting work on your fork ❤️

Thank u @oafx

**Comment by Akababa** [comment]
Thanks @oafx and @ben-bay ! I was busy today so I'm grateful for your help.

**Pull request merged**
